# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_windows
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_windows)
  SpaceGame_config = debug_windows

else ifeq ($(config),debug_linux)
  SpaceGame_config = debug_linux

else ifeq ($(config),development_windows)
  SpaceGame_config = development_windows

else ifeq ($(config),development_linux)
  SpaceGame_config = development_linux

else ifeq ($(config),release_windows)
  SpaceGame_config = release_windows

else ifeq ($(config),release_linux)
  SpaceGame_config = release_linux

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := SpaceGame

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

SpaceGame:
ifneq (,$(SpaceGame_config))
	@echo "==== Building SpaceGame ($(SpaceGame_config)) ===="
	@${MAKE} --no-print-directory -C Build -f Makefile config=$(SpaceGame_config)
endif

clean:
	@${MAKE} --no-print-directory -C Build -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_windows"
	@echo "  debug_linux"
	@echo "  development_windows"
	@echo "  development_linux"
	@echo "  release_windows"
	@echo "  release_linux"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   SpaceGame"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"